name: nfe_cte_viewer
description: A new Flutter package for generating SEFAZ-compliant DANFE and DACTE PDFs.
version: 0.0.1
homepage: https://domanisistemas.com.br

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.11.1
  intl: ^0.18.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
